/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.maiconfz.spring_rest_only_vs_rabbitmq_processing.java-library-conventions")
}

dependencies {
    api(project(":list"))
}
