/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.maiconfz.spring_rest_only_vs_rabbitmq_processing.utilities;

import io.maiconfz.spring_rest_only_vs_rabbitmq_processing.list.LinkedList;

public class StringUtils {
    public static String join(LinkedList source) {
        return JoinUtils.join(source);
    }

    public static LinkedList split(String source) {
        return SplitUtils.split(source);
    }
}
