spring:
    datasource:
        url: postgresql://localhost:5432/sa
        username: sa
        password: sa
        driverClassName: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true

