/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.maiconfz.spring_rest_only_vs_rabbitmq_processing.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("io.maiconfz.spring_rest_only_vs_rabbitmq_processing.app.App")
}
