/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.maiconfz.spring_rest_only_vs_rabbitmq_processing.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
